default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: su
  host: localhost
  pool: 5

development:
  <<: *default
  database: multitenant_app_development

test:
  <<: *default
  database: multitenant_app_test

production:
  <<: *default
  database: multitenant_app_production
  username: multitenant
  password: <%= ENV["MULTITENANT_APP_DATABASE_PASSWORD"] %>
